locale = "en"
label = "English"
weight = 1
title = "Arnaut"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/mirza-logo-white-small.png"
  secondaryLogo = "img/mirza-logo-black-small.png"
  description = "Arnaut's personal website"
  images = ['img/circle-space.jpg']
  copyright = "&copy; { year } [Mirza Arnaut](https://github.com/arunoruto/website)"

[params.author]
  name = "Mirza Arnaut"
  # image = "https://arnaut.me/data/me3.jpg"
  image = "img/me-anime.jpg"
  headline = "Researcher. Climber. DIYer."
  bio = "Tinkering since 1996"
  links = [
    { email = "mailto:mirza.arnaut@tu-dortmund.de" },
    { link = "https://bv.etit.tu-dortmund.de/professur/arbeitsgruppe/arnaut/" },
    # { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
    # { apple = "https://www.apple.com" },
    # { blogger = "https://username.blogspot.com/" },
    # { codepen = "https://codepen.io/username" },
    # { dev = "https://dev.to/username" },
    # { discord = "https://discord.gg/invitecode" },
    # { dribbble = "https://dribbble.com/username" },
    # { facebook = "https://facebook.com/username" },
    # { flickr = "https://www.flickr.com/photos/username/" },
    # { foursquare = "https://foursquare.com/username" },
    { github = "https://github.com/arunoruto" },
    # { gitlab = "https://gitlab.com/username" },
    # { google = "https://www.google.com/" },
    # { hashnode = "https://username.hashnode.dev" },
    # { instagram = "https://instagram.com/username" },
    # { keybase = "https://keybase.io/username" },
    # { kickstarter = "https://www.kickstarter.com/profile/username" },
    # { lastfm = "https://lastfm.com/user/username" },
    { linkedin = "https://www.linkedin.com/in/mirza-arnaut-78589b14b/" },
    # { mastodon = "https://mastodon.instance/@username" },
    # { medium = "https://medium.com/username" },
    # { microsoft = "https://www.microsoft.com/" },
    { orcid = "https://orcid.org/0000-0002-1631-7083" },
    # { patreon = "https://www.patreon.com/username" },
    # { pinterest = "https://pinterest.com/username" },
    # { reddit = "https://reddit.com/user/username" },
    { researchgate = "https://www.researchgate.net/profile/Mirza_Arnaut" },
    # { slack = "https://workspace.url/team/userid" },
    # { snapchat = "https://snapchat.com/add/username" },
    # { soundcloud = "https://soundcloud.com/username" },
    # { stack-overflow = "https://stackoverflow.com/users/userid/username" },
    # { steam = "https://steamcommunity.com/profiles/userid" },
    # { telegram = "https://t.me/username" },
    # { tiktok = "https://tiktok.com/@username" },
    # { tumblr = "https://username.tumblr.com" },
    # { twitch = "https://twitch.tv/username" },
    # { twitter = "https://twitter.com/username" },
    # { x-twitter = "https://twitter.com/username" },
    # { whatsapp = "https://wa.me/phone-number" },
    # { youtube = "https://youtube.com/username" },
    # { xing = "https://www.xing.com/profile/Mirza_Arnaut" },
    # { ko-fi = "https://ko-fi.com/username" },
  ]
